### ISSUE TITLE
病理图像归一化问题

### ISSUE THREAD

**Issue by Hanminghao** [lin-lcx/HGCN#1]
作者您好，阅读了您以及王连生教授的文章后感觉受益匪浅，想问下您的病理图像的normalize是使用的什么方法？

**Comment by Hanminghao** [comment]
还有一个问题，如果一个病人有多个wsi文件，您是如何处理t_img_fea.pkl中相同病人不同wsi文件的信息的

**Comment by Ayakax** [comment]
> 作者您好，阅读了您以及王连生教授的文章后感觉受益匪浅，想问下您的病理图像的normalize是使用的什么方法？

您好，想问一下哪里可以看到这篇文章的全文呀，IEEE上我下载PDF一直失败

**Comment by Hanminghao** [comment]
> > 作者您好，阅读了您以及王连生教授的文章后感觉受益匪浅，想问下您的病理图像的normalize是使用的什么方法？
> 
> 您好，想问一下哪里可以看到这篇文章的全文呀，IEEE上我下载PDF一直失败

节点挂到美国应该就可以下载了

**Comment by Ayakax** [comment]
> > > 作者您好，阅读了您以及王连生教授的文章后感觉受益匪浅，想问下您的病理图像的normalize是使用的什么方法？
> > 
> > 
> > 您好，想问一下哪里可以看到这篇文章的全文呀，IEEE上我下载PDF一直失败
> 
> 节点挂到美国应该就可以下载了

感谢感谢！

**Comment by lin-lcx** [comment]
> 

感谢您的支持！
病理图像并没有使用额外的normalize，用的都是10倍下的原图。每个病例只随机选择一幅WSI作为输入数据。

**Comment by Hanminghao** [comment]
> > 
> 
> 感谢您的支持！ 病理图像并没有使用额外的normalize，用的都是10倍下的原图。每个病例只随机选择一幅WSI作为输入数据。

感谢回复，明白了。
