### ISSUE TITLE
请问关于论文中的图4

### ISSUE THREAD

**Issue by lmxmercy** [lin-lcx/HGCN#2]
您好！
非常棒的工作！也感谢您把代码release出来供大家学习！
想请问下论文中图4的“Interpretation of the proposed framework”关于WSI的heatmap以及“Integrated gradient analysis of genomic profile”是怎么生成的呢，请问这部分代码会放出来嘛，或是参照了哪篇文章或code，期待您的回复！

**Comment by lin-lcx** [comment]
WSI的heatmap通过导出GlobalAttention pool的结果画出。
“Integrated gradient analysis of genomic profile”使用的是[captum](https://github.com/pytorch/captum)库导出。
:)

**Comment by lmxmercy** [comment]
感谢您的回复！请问这部分代码方便公开嘛（礼貌问
